#!/usr/bin/env bash
adduser --disabled-password --gecos "" asyn
sudo echo "asyn ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
mkdir -p /home/asyn/.ssh && cp /root/.ssh/authorized_keys /home/asyn/.ssh/authorized_keys
chmod 600 /home/asyn/.ssh/authorized_keys && chown -R asyn:asyn /home/asyn/.ssh
echo "America/Los_Angeles" > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata
date
sed -i '$ a vm.panic_on_oom=1\nkernel.panic=10' /etc/sysctl.conf
sed -i '$ a tmpfs     /run/shm     tmpfs     defaults,noexec,nosuid     0     0' /etc/fstab
sed -i "s/PermitRootLogin yes/PermitRootLogin no/" /etc/ssh/sshd_config
sed -i "s/#PasswordAuthentication yes/PasswordAuthentication no/" /etc/ssh/sshd_config
sed -i "s/UsePAM yes/UsePAM no/" /etc/ssh/sshd_config
sed -i "s/IPV6=yes/IPV6=no/" /etc/default/ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw --force enable
echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
apt-get -y update && wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -
apt-get -y install fail2ban ntp monit


# apt-get -y newrelic-sysmond 
# nrsysmond-config --set license_key=39d84434c7725f2754cf12b0e5f5777215176273
# /etc/init.d/newrelic-sysmond start

# cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local && sudo sed -i "/^\[ssh-ddos\]$/,/^\[/s/enabled[[:blank:]]*=.*/enabled = true/" /etc/fail2ban/jail.local
# service fail2ban restart
# service ssh restart
# -----------------------------------------------------------------------------------
#
#     curl https://raw.githubusercontent.com/lawrrn/installer/master/auto-base | bash
#
#
