#!/usr/bin/env bash

# FIREWALL
sudo ufw allow www
sudo ufw allow https
sudo ufw disable
sudo ufw --force enable

# vim ~/.bashrc
# -------------------------------------------
# export RBENV_ROOT="${HOME}/.rbenv"
#
# if [ -d "${RBENV_ROOT}" ]; then
#  export PATH="${RBENV_ROOT}/bin:${PATH}"
#  eval "$(rbenv init -)"
# fi
# -------------------------------------------
# source .bashrc


# RUN STUFF
sudo apt-get -y update
sudo apt-get -y install curl git-core python-software-properties build-essential zlib1g-dev libssl-dev libreadline-gplv2-dev libcurl4-openssl-dev npm

# NGINX
sudo add-apt-repository -y ppa:nginx/stable
sudo apt-get -y update
sudo apt-get -y install nginx
# service nginx status

curl -L https://raw.github.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash

sudo rbenv bootstrap-ubuntu-12-04
rbenv install 2.1.2 --verbose
rbenv global 2.1.2
ruby -v

echo "gem: --no-ri --no-rdoc" >> ~/.gemrc

gem install bundler --no-ri --no-rdoc
gem install rake
rbenv rehash
bundle -v

# IMAGE PROCESSING
sudo aptitude install -y imagemagick


# curl https://raw.githubusercontent.com/lawrrn/installer/master/part3 | bash

