#!/usr/bin/env bash

# vim ~/.bashrc
# -------------------------------------------
# export RBENV_ROOT="${HOME}/.rbenv"
#
# if [ -d "${RBENV_ROOT}" ]; then
#  export PATH="${RBENV_ROOT}/bin:${PATH}"
#  eval "$(rbenv init -)"
# fi
# -------------------------------------------
# source .bashrc

curl -L https://raw.github.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash

sudo rbenv bootstrap-ubuntu-12-04
rbenv install 2.1.3
rbenv global 2.1.3
ruby -v
