#!/usr/bin/env bash
adduser --disabled-password --gecos "" asyn
sudo echo "asyn ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
mkdir /home/asyn/.ssh

# SECURITY
apt-get -y update
apt-get -y install fail2ban ntp monit

# NTP
echo "America/Los_Angeles" > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata
date

# MONIT
ps aux | grep monit
service monit status
# vim /etc/monit/monitrc
service monit restart

# FAIL2BAN
cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

# REBOOT OUT OF MEMORY
sed -i '$ a vm.panic_on_oom=1\nkernel.panic=10' /etc/sysctl.conf
# vim /etc/sysctl.conf

# SHARED MEMORY READY ONLY
sed -i '$ a tmpfs     /run/shm     tmpfs     defaults,noexec,nosuid     0     0' /etc/fstab
# vim /etc/fstab


# curl https://raw.githubusercontent.com/lawrrn/installer/master/part1 | bash

# scp .ssh/id_rsa.pub root@x.x.x.x:/home/asyn/.ssh/authorized_keys

